version: '3.8'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    hostname: zookeeper1
    container_name: zookeeper1
    extra_hosts:
      - "datanode1:172.30.0.3"
      - "datanode2:172.30.0.5"
      - "datanode3:172.30.0.7"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:12888:3888;datanode2:22888:3888;datanode3:32888:3888
      ZOOKEEPER_MAX_CLIENT_CNXNS: 60
      ZOOKEEPER_DATA_DIR: /var/lib/zookeeper
      LOG_DIR: /var/log/zookeeper
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - ./zookeeper-data/data:/var/lib/zookeeper/data
      - ./zookeeper-data/log:/var/lib/zookeeper/log
      - ./zookeeper-varlog:/var/log/zookeeper
    #network_mode: host
    networks:
      kafka-cluster-net:
        ipv4_address: 172.30.0.3
    ports:
      - "12181:2181"
      - "12888:2888"
      - "13888:3888"

  kafka1:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    hostname: kafka1
    container_name: kafka1
    extra_hosts:
      - "datanode1:172.30.0.3"
      - "datanode2:172.30.0.5"
      - "datanode3:172.30.0.7"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:12181,datanode2:22181,datanode3:32181/kafka"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.30.0.4:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_DATA_DIR: /var/lib/kafka
      KAFKA_LOG_RETENTION_HOURS: 168
      LOG_DIR: /var/log/kafka
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-data:/var/lib/kafka/data
      - ./kafka-varlog:/var/log/kafka
    depends_on:
      - zookeeper1
    #network_mode: host
    networks:
      kafka-cluster-net:
        ipv4_address: 172.30.0.4
    ports:
      - "19092:9092"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    hostname: kafdrop
    container_name: kafdrop
    extra_hosts:
      - "datanode1:172.30.0.4"
      - "datanode2:172.30.0.6"
      - "datanode3:172.30.0.8"
    environment:
      KAFKA_BROKERCONNECT: "datanode1:19092,datanode2:29092,datanode3:39092"
    depends_on:
      - kafka1
    networks:
      kafka-cluster-net:
        ipv4_address: 172.30.0.2
    ports:
      - "19000:9000"

networks:
  kafka-cluster-net:
    name: kafka-cluster-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
